### PR TITLE
migrate to v3

### PR DESCRIPTION
**Pull request by jaumard**

### CODE REVIEW

**Comment by jaumard** [comment]
TravisCI crash on node 7 because or trails dependencies, waiting for the team feedback on this

**Comment by jaumard** [comment]
Yeah maybe when more docs and more example show how resolvers works we can try to be compliant with them :)

**Comment by scott-wyatt** [comment]
I'm guessing we need to release this as 3.0.1 or 3.1.0?

**Comment by jaumard** [comment]
I put 3.1.0 on the package.json file as there some important changes

**Comment by scott-wyatt** [comment]
Cool, merge if you please :-)

**Pull request merged**
