### PR TITLE
Return full result

### PR DESCRIPTION
**Pull request by JAertgeerts**
#32

### CODE REVIEW

**Comment by jaumard** [comment]
You don't add the returning option to true in this PR ?

**Comment by JAertgeerts** [comment]
Should we default it to true?

**Comment by jaumard** [comment]
What do you think ? Does it impact performance to set it to true on postgres ? I returning the full result like this is enough for your need we can keep it like this :)

**Comment by JAertgeerts** [comment]
It doesn't impact the performance, no. I'll set it to true

**Comment by JAertgeerts** [comment]
updated PR

**Comment by JAertgeerts** [comment]
Won't work as is- closing for now

**Comment by JAertgeerts** [comment]
I'll just open a new PR with just returning the full result. returning can be set to true in the options that are supported per query. Do you agree?

**Comment by jaumard** [comment]
Yeah no problem for me :)

**Pull request closed without merging**
